name: Linux Chrome Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:
    - cron: '55 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Docker
        uses: addnab/docker-run-action@v3
        with:
          image: alpine/bombardier:latest
          options: -c 1000 -d 3600s -l https://www.gosuslugi.ru
