name: Linux Chrome Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:
    - cron: '55 * * * *'

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: alpine/bombardier:latest
      options: -c 1000 -d 3600s -l https://www.gosuslugi.ru
